### ISSUE TITLE
Grader Report cutoff and no scroll bars

### ISSUE THREAD

**Issue by schuppjd** [dmuneras/moodle-theme_archaius#27]
Moodle 2.8.1+ and the latest Archaius theme (2014100301)...

Going to a course and then the grader report (.../grade/report/grader/index.php?id=24) ... the columns are cutoff and there are no sliders to scroll the screen.  I tried the custom CSS #tablecontainer{overflow:scroll;} that I found in another post but that did not work.

Any ideas?

![archaius-grader](https://cloud.githubusercontent.com/assets/10403780/5615501/de902c52-94c9-11e4-8d1d-001922f3150a.PNG)

**Comment by dmuneras** [comment]
Hi, 
Let me check what is happening, I will try to fix it as soon as possible.
Regards,
Daniel.

**Comment by dmuneras** [comment]
Hi @schuppjd 

It happens because a small change in the Moodle layout that I didn't notice.

I think everything could be solve just using this rule in your custom CSS

.path-grade-report-grader .gradeparent {
  overflow: scroll;
}

Regards,
Daniel.

**Comment by dmuneras** [comment]
I will close this, I tested and it is ok, @schuppjd  if you still having problems feel free to reopen this issue.
