### ISSUE TITLE
Scroller on frontpage covers/disables Label

### ISSUE THREAD

**Issue by dave1966uk** [dmuneras/moodle-theme_archaius#29]
Hi

I have a Label in the centre of the page that has a table with icons to access the various courses.  However if I enable the Scroller, the top-most label is not only cover but disappears (though the space it would have occupied still seems to be there as any subsequent labels start further down the page).

Thanks
![one](https://cloud.githubusercontent.com/assets/1949822/5989561/19d50ff2-a984-11e4-9bee-2eb7509355f6.png)
![two](https://cloud.githubusercontent.com/assets/1949822/5989562/212f6090-a984-11e4-9e08-3d65445f5be5.png)

**Comment by dmuneras** [comment]
HI @dave1966uk 

Could you give me the URL of your website to take a look of the page and don have to replicate the scenario?

Regards,
Daniel.

**Comment by dave1966uk** [comment]
Dear Daniel

 

Many thanks for your email.

 

The link is:

 

http://intranet.catscanterbury.com/moodle/

 

Best wishes

 

David

**Comment by dmuneras** [comment]
Hi @dave1966uk,

I think you can solve the problem by adding the following line to your custom css:

#home-page{overflow:auto;}

I have to check if this is a good solution to add it to my theme permanently, if not, I have to find a better solution.

Let me know if it works.

Best regards,
Daniel.

**Comment by dave1966uk** [comment]
Dear Daniel

 

Yes that fixed it.  Thank you.

 

I have noticed a weird thing.  When as a teacher I choose a course, it appears like below.  Where are the blocks on the left and right?  I ask as I need to enter grades and usually the grades option is in a block on the left.  Indeed the menu at the top seems to have gone as well!

 

Best wishes

 

David

**Comment by dmuneras** [comment]
Hi @dave1966uk 

Could you please give your version of Moodle, version of Archaius and share the image of the last thing you describe.

Daniel.

**Comment by dave1966uk** [comment]
Hi Daniel

 

Moodle version Moodle 2.6.2+ (Build: 20140327)

 

AT this stage, all ok…

 



 

I select say “Computing C 2014-2015” course and I see this:

 



 

The blocks and top menu have gone.  Pressing back and everything is normal again.  Does it for all my courses.

 

Best wishes

 

David

**Comment by dmuneras** [comment]
I don't have a usarname and password to watch the course in the platform and you are not attaching the images from github, so, I can't se anything. :smile:

**Comment by dave1966uk** [comment]
Hi Daniel

I have emailed you an account login.

the screen before chosing a course and then the course iteself are below.

Best wishes

David
![p1](https://cloud.githubusercontent.com/assets/1949822/5993751/3ab389b4-aa52-11e4-9041-b05d57d9c546.png)
![p2](https://cloud.githubusercontent.com/assets/1949822/5993752/3e41c87a-aa52-11e4-8119-8680befd21b3.png)

**Comment by dmuneras** [comment]
Hi @dave1966uk 

I think I know what is the problem,  usually it happens when you use blocks or plugins that use jQuery and don't use the standard way to include it. Could you tell me which blocks and modules you are using in that course?, because I am 90% sure the problem is there.

Daniel.

**Comment by dave1966uk** [comment]
Hi Daniel

 

On the left: Login, Navigation, Administration, an HTML block for links, Activities

On the right: Recent Activity, Upcoming events, and a block I made for students to report issues (basically some PHP to check they are logged in and a link to the report form)

 

Best wishes

 

David
