### ISSUE TITLE
How to sort courses in "My Courses" ascending, not descending?

### ISSUE THREAD

**Issue by sgendry** [dmuneras/moodle-theme_archaius#33]
My courses display in ascending order in the body, but in descending order in the top menu.
Is that a theme setting or something I need to change somewhere in moodle?

Daniel: Did I mention you were outstanding?

**Comment by dmuneras** [comment]
Hi @sgendry,

I am just retrieving the user courses from Moodle API, but I am not taking care of the order, to be able to do that I have to modify a function. 

Conclusion: It is possible and it seems to be easy to implement, but at the moment is not implemented. 

Regards,
Daniel.
