### ISSUE TITLE
Activity completion report problem

### ISSUE THREAD

**Issue by vaughany** [dmuneras/moodle-theme_archaius#35]
Hi there. We've come across a problem with the latest Archaius release (2015011900) on Moodle 2.8 (build 20150205).  The problem is with the activity completion report located at report/progress/?course=xx

When using the default theme Clean, a large report can be scrolled left and right to see all the columns (note the scrollbar at the bottom):

![report-clean](https://cloud.githubusercontent.com/assets/381767/6185038/53b24488-b361-11e4-91f2-6fb04bbd0e7a.jpg)

However, if you view the same report (from the same course) with the latest Archaius theme you cannot scroll left or right, and some (or in this case, many) columns are hidden from view with no way to get to them:

![report-archaius](https://cloud.githubusercontent.com/assets/381767/6185050/801f552e-b361-11e4-82c9-e0b5e345151f.jpg)

**Comment by dmuneras** [comment]
Hi @vaughany 

Let me check what happen, but I think it is the same problem I already solve for other person.

https://github.com/dmuneras/moodle-theme_archaius/issues/27

Regards,
Daniel.

**Comment by dmuneras** [comment]
Hi @vaughany 

It wasn't the same problem but it was so similar. 

If you add this to your CSS I hope everything is going to be ok:

#completion-progress-wrapper{overflow:scroll;}

Pd. Sorry for the huge amount of things I've made you add to your custom CSS, it is just that I am trying to finish my master degree and I get a new job, so, I haven't have enough time to fix all this small details and make a release. I prefer to double check all this fixes before add it to my theme.

http://quick.as/2kerfdkj

**Comment by dmuneras** [comment]
I will close the issue but feel free to reopen it if it doesn't work.

**Comment by vaughany** [comment]
Hi Daniel. Sorry to not get back to you sooner, I was out of the country and not thinking about work! :)

I've added the code into the theme and we can now scroll around, so thank you very much for that. And no apologies necessary!  I (and I am sure, many others) are grateful for your development and support of this theme.

Regards,

Paul.

**Comment by dmuneras** [comment]
Great!!, BTW,  I want holidays too.

Daniel.
