### ISSUE TITLE
Second header not showing. (the one with Moodle community, moodle.com etc on in screenshot)

### ISSUE THREAD

**Issue by dcuk6** [dmuneras/moodle-theme_archaius#37]
Running 2.9 and having issues getting the second header to show up.

Theres a space there for it and you can highlight a white block that runs across the page but cant see anything there.

Loving the rest so far.

Thanks

**Comment by dmuneras** [comment]
Hi @dcuk6 

I am sorry, I know it should be annoying, but I haven't released a version for moodle 2.9.

Best regards,
Daniel.
