### ISSUE TITLE
Strange CSS

### ISSUE THREAD

**Issue by temin** [dmuneras/moodle-theme_archaius#44]
I believe I found an error in theme's CSS styles. In archaius.css file on line 452 there is a _display:none_ property that hides the editing icons in the central column of the dashboard (with editing on).
I've replaced it with _display:inline_ and icons returned. So far didn't see any unwanted effect.

**Comment by dmuneras** [comment]
Hi @temin,

I guest it have to be something I probably did because of the blocks in the central area, or probably it is something I changed for a private project an I push here.

Thanks a lot for report it,
Daniel.
