### ISSUE TITLE
Cannot access the show/hide option for topics

### ISSUE THREAD

**Issue by kirbynk** [dmuneras/moodle-theme_archaius#7]
Hi,

This is a great theme but the show/hide icon for topics is not visible. I have tried the theme on several different browsers and versions of Moodle.  I have looked around within the theme for clues but have not been successful. Appreciate any help. Thanks.

![screenshot 1](https://f.cloud.github.com/assets/2194113/943818/f03e2934-0269-11e3-917b-71b0ef80b92d.png)

**Comment by anabelaa** [comment]
Hi, I have the same problem, i have install moodle 2.3 with Archaius theme but, but the show/hide icon for topics is not visible.
How can i solvet it.

Thanks

**Comment by dmuneras** [comment]
@anabelaa  which version of the theme are you using?

**Comment by dmuneras** [comment]
I think these are the same issue: https://github.com/dmuneras/moodle-theme_archaius/issues/34
